name: Go Format and Commit

on:
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

env:
  GO_VERSION: ${{ vars.GO_VERSION }}

jobs:
  go-format:
    name: Format Go Files and Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Format Go Code
        run: |
          # Get the list of changed .go files in the pull request
          files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep '\.go$') || true
          if [ -n "$files" ]; then
            echo "Formatting the following .go files: $files"
            for file in $files; do
              go fmt "$file"
            done
          else
            echo "No Go files changed in this pull request."
          fi

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Apply Go file formatting (via gofmt and goimports)"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            echo "No formatting changes to commit."
          fi
        
